# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            B2B Saas Pricing 
tagline:          'A collection of thoughts'
description:      'A collection of thoughts, ideas and suggestions about how to properly price B2B SaaS products and services.'
url:              http://mikhaill.github.io
baseurl:          /

author:
  name:           'Mikhail Ledvich'
  url:            https://twitter.com/mrmikhail

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mikhaill/mikhaill.github.io
